config/routes.rb
Rails.application.routes.draw do

  resources :requests

  resources :projects

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy'#, :as => :destroy_user_session
  end

  get "welcome/dashboard"
  
  root to: "welcome#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  #has_many :invoices
  #has_many :messages
  #has_one :contract
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :requests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.location = auth.info.location
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.role == "dev"
      welcome_dashboard_path
    else
      requests_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    #authorize @project
    if @project.save
      redirect_to @project, notice: "Project was created successfully"
    else
      flash[:error] = "Project was not created. Please try again."
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    #authorize @project
  end

  def edit
  end

  def index
    @projects = current_user.projects 
    @customer_projects = Project.where(poc: current_user.id)
  end

  def update
  end

  private

  def project_params
    params.require(:project).permit(:name, :url, :host, :poc)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  def new
    @request = Request.new
    #authorize @request, role != dev
  end

  def create
    @request = current_user.requests.build(request_params)
    #authorize @request

    if @request.save
      redirect_to @request, notice: "Request successfully created"
    else
      flash[:error] = "Request failed. Please try again."
      render :new
    end
  end

  def show
    @request = Request.find(params[:id])
    #authorize @request
  end

  def edit
    @request = Request.find(params[:id])
    #authorize @request
  end

  def update
    @request = Request.find(params[:id])

    if @request.update_attributes!(request_params)
      redirect_to @request, notice: "Request has been updated"
    else
      flash[:error] = "There was an error processing your update. Please try again."
      render :edit
    end
  end

  def index
    @requests = current_user.requests
  end

  private

  def request_params
    params.require(:request).permit(:purpose, :timeline, :budget, :users_supported, :need_hosting, :poc, :phone, :remarks)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @user.skip_confirmation!

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @dev = User.where(role: "dev")
  end

  def dashboard
    @projects = Project.all
    @requests = Request.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "devTheory", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user.role.nil? %>
          <li><%= link_to "My Applications", projects_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Requests <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Active Requests", requests_path %></li>
              <li><%= link_to "New Request", new_request_path %></li>
            </ul>
          </li> 
          
        <% else %>
          <li><%= link_to "Dashboard", welcome_dashboard_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>

      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <%= flash[:alert] %>
      </div>
    <% end %>
<%= yield %>
</body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<%= render "layouts/navbar" %>
<br />

<div class="col-md-6">

  <% if @projects.count > 0 %>
    <h2>Projects </h2>
    <small>Click on a project to see more information about it.</small>
      <ul class="list-group">
        <% @projects.each do |project| %>
          <li class="list-group-item"><%= link_to project.name, project_path(project) %></li>
        <% end %>
      </ul>
  <% else %>
    <p>You have no active applications. Once your application development has begun, you will be able to see it's current status here. If you would like to request a quote and get a new application going, please click <strong><%=link_to "Here", new_request_path %></strong> to begin the process.</p>
  <% end %>

</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/edit.html.erb
<%= render "layouts/navbar" %>
<br >

<div class="col-md-6">
  <%= form_for(@request) do |f| %>
  <div class="form-group">
      <%= f.label :purpose %>
      <%= f.text_field :purpose, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :timeline %>
      <%= f.text_field :timeline, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :budget %>
      <%= f.text_field :budget, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :users_supported %>
      <%= f.text_field :users_supported, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :need_hosting %>
      <%= f.text_field :need_hosting, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :point_of_contact %>
      <%= f.text_field :poc, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :contact_number %>
      <%= f.text_field :phone, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :remarks %>
      <%= f.text_area :remarks, class: 'form-control' %>
    </div>

    <%= f.submit "Update", class: 'btn btn-info' %>
  <% end %>
</div>

app/views/requests/index.html.erb
<%= render "layouts/navbar" %>
<br >
<div class="col-md-6">
  <% if current_user.role == nil %>

    <% if @requests.count > 0 %>
      <h2>Requests </h2>
      <small>Click on a request to see more information about it.</small>
        <ul class="list-group">
          <% @requests.each do |request| %>
            <li class="list-group-item"><%= link_to request.purpose, request_path(request) %></li>
          <% end %>
        </ul>
    <% else %>
      <p>You have no active requests. If you would like to request a quote, please click on <strong>New Request</strong> above to begin.</p>
    <% end %>

  <% else %>

    <% if @requests.count > 0 %>
      <h2>Requests </h2>
      <small>Click on a request to see more information about it.</small>
        <ul class="list-group">
          <% @requests.each do |request| %>
            <li class="list-group-item"><%= link_to request.purpose, request_path(request) %></li>
          <% end %>
        </ul>
    <% else %>
      <p>You have no active requests.</p>
    <% end %>

  <% end %>
</div>

app/views/requests/new.html.erb
<%= render "layouts/navbar" %>
<br >
<div class="col-md-6">
  <p>Thank you for your interest in contacting us about your needs. Please use the form below to request a quote from us.</p>
  <%= form_for (@request) do |f| %>

  <div class="form-group">
    <%= f.label :purpose %>
    <%= f.text_field :purpose, class: 'form-control', placeholder: 'What is the main goal of your application?' %>
  </div>

  <div class="form-group">
    <%= f.label :timeline %>
    <%= f.text_field :timeline, class: 'form-control', placeholder: 'How soon would you like your application to be operational?' %>
  </div>

  <div class="form-group">
    <%= f.label :budget %>
    <%= f.text_field :budget, class: 'form-control', placeholder: 'Do you have a planned budget range for the application?' %>
  </div>

  <div class="form-group">
    <%= f.label :users_supported %>
    <%= f.text_field :users_supported, class: 'form-control', placeholder: 'About how many users are you looking to support?' %>
  </div>

  <div class="form-group">
    <%= f.label :need_hosting? %> We can take care of securing a domain (www.your-address.com) and hosting (space for files needed to run your site) for you.
    <%= f.text_field :need_hosting, class: 'form-control', placeholder: 'Would you like us to handle hosting/domain for you?' %>
  </div>

  <div class="form-group">
    <%= f.label :point_of_contact? %>
    <%= f.text_field :poc, class: 'form-control', placeholder: 'Who will be making decisions regarding the product?' %>
  </div>

  <div class="form-group">
    <%= f.label :contact_number? %>
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Please provide a number where we can reach you' %>
  </div>


  <div class="form-group">
    <%= f.label :remarks %>
    <%= f.text_area :remarks, class: 'form-control', placeholder: "Any additional information you'd like to provide?" %>
  </div>

  <%= f.submit "Submit", class: 'btn btn-info' %>
  <% end %>

</div>

app/views/requests/show.html.erb
<%= render "layouts/navbar" %>
<br >

<div class="col-md-6">
  <ul class="list-group">
    <li class="list-group-item"><strong>Purpose:</strong> <%= @request.purpose %></li>
    <li class="list-group-item"><strong>Timeline:</strong> <%= @request.timeline %></li>
    <li class="list-group-item"><strong>Budget:</strong> <%= @request.budget %></li>
    <li class="list-group-item"><strong>Users supported:</strong> <%= @request.users_supported %></li>
    <li class="list-group-item"><strong>Need hosting?:</strong> <%= @request.need_hosting %></li>
    <li class="list-group-item"><strong>Remarks:</strong> <%= @request.remarks %></li>
  </ul>
  <%= link_to "Edit", edit_request_path(@request), class: "btn btn-warning" %>
</div>

app/views/requests/update.html.erb
<h1>Requests#update</h1>
<p>Find me in app/views/requests/update.html.erb</p>

app/views/welcome/dashboard.html.erb
<%= render "layouts/navbar" %>
<br >

<div class="col-md-6">
  <h2>Active Projects</h2>
  <div class="panel panel-info">
    <div class="panel-body">
      <ul class="list-group">
        <% if @projects.count > 0 %>
          <% @projects.each do |project| %>
            <li class="list-group-item"><%= link_to project.name, project_path(project) %></li>
          <% end %>
        <% else %>
          <li class="list-group-item">You have no projects.</li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">Click on a project to learn more about it.</div>
  </div>
</div>

<div class="col-md-6">
  <h2>Requests</h2>
  <div class="panel panel-info">
    <div class="panel-body">
      <ul class="list-group">
        <% if @requests.count > 0 %>
          <% @requests.each do |request| %>
            <li class="list-group-item"><%= link_to request.purpose, request_path(request) %></li>
          <% end %>
        <% else %>
          <li>You have no requests.</li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">Click on a request to learn more about it.</div>
  </div>
</div>